// Single source of truth for supported formats.
// Keep this list in sync with the format-pill UI and SEO doorway page generator.

export const FORMATS = [
  {
    id: "png",
    label: "PNG",
    mime: "image/png",
    ext: "png",
    lossy: false,
    tagline: "Lossless, transparency-friendly raster.",
    blurb:
      "PNG is the standard for graphics that need pixel-exact fidelity and an alpha channel — logos, screenshots, UI exports.",
    pros: ["Lossless quality", "Alpha (transparency)", "Universal browser support"],
    cons: ["Larger files than JPG/WebP for photos", "No animation"],
  },
  {
    id: "jpg",
    label: "JPG",
    aliases: ["jpeg"],
    mime: "image/jpeg",
    ext: "jpg",
    lossy: true,
    tagline: "The web's photographic workhorse.",
    blurb:
      "JPG uses lossy compression and is the right pick for photographs and natural scenes when file size matters.",
    pros: ["Smallest size for photos", "Universal compatibility"],
    cons: ["No transparency", "Re-saves degrade quality"],
  },
  {
    id: "webp",
    label: "WebP",
    mime: "image/webp",
    ext: "webp",
    lossy: true,
    tagline: "Modern format, ~30% smaller than JPG.",
    blurb:
      "WebP gives you JPG-class compression with alpha-channel support — the modern default for web imagery.",
    pros: ["Smaller than PNG and JPG", "Supports transparency", "Animation supported"],
    cons: ["Older software may not open it"],
  },
  {
    id: "gif",
    label: "GIF",
    mime: "image/gif",
    ext: "gif",
    lossy: false,
    tagline: "Indexed colour, animation-capable.",
    blurb:
      "GIF caps at 256 colours and is mostly used today for short, lightweight animations and simple sprite graphics.",
    pros: ["Universal animation support", "Tiny for flat graphics"],
    cons: ["256-colour ceiling", "Larger than WebP for the same content"],
  },
  {
    id: "svg",
    label: "SVG",
    mime: "image/svg+xml",
    ext: "svg",
    lossy: false,
    tagline: "Vector — scale to any size, zero quality loss.",
    blurb:
      "SVG is XML-based vector. Generated by exporting a raster wrapped in an SVG container, so true vectorization requires a dedicated tracing tool.",
    pros: ["Infinite scalability", "Tiny for line art / icons", "Stylable with CSS"],
    cons: ["Not ideal for photographs", "Raster→SVG is an embed, not a trace"],
  },
  {
    id: "ico",
    label: "ICO",
    mime: "image/x-icon",
    ext: "ico",
    lossy: false,
    tagline: "Windows favicon container.",
    blurb:
      "ICO holds one or more icon sizes in a single file — the canonical favicon format for browsers that still ask for it.",
    pros: ["Multi-size favicons in one file", "Universal favicon support"],
    cons: ["Designed for small icons (256px max)"],
  },
  {
    id: "tiff",
    label: "TIFF",
    aliases: ["tif"],
    mime: "image/tiff",
    ext: "tiff",
    lossy: false,
    tagline: "Print + archival raster.",
    blurb:
      "TIFF is the high-fidelity format used by scanners, print pipelines, and image archives.",
    pros: ["Lossless", "Supports CMYK + alpha", "Archival standard"],
    cons: ["Large file sizes", "Limited browser support"],
  },
];

export const FORMAT_IDS = FORMATS.map((f) => f.id);

export function getFormat(id) {
  if (!id) return null;
  const lower = String(id).toLowerCase();
  return (
    FORMATS.find(
      (f) => f.id === lower || (f.aliases && f.aliases.includes(lower)),
    ) || null
  );
}

// Generate all "from-to" pairs for SEO doorway pages.
// 7 formats × 6 = 42 doorway routes.
export function getAllConversionPairs() {
  const pairs = [];
  for (const from of FORMATS) {
    for (const to of FORMATS) {
      if (from.id === to.id) continue;
      pairs.push({ from, to, slug: `${from.id}-to-${to.id}` });
    }
  }
  return pairs;
}
